### ISSUE TITLE
Fails on Ubuntu 14.04 with Nodejs 4.0.0

### ISSUE THREAD

**Issue by adam-stokes** [craigshoemaker/electron-api-demos#1]
Just fyi, not sure if Linux and/or Node 4 is supported or not for this (i couldn't find a test matrix):

```
[~/P/electron-api-demos]                                                                                             
‹master› »»»» npm install                                                                                  0|10:32:01
npm WARN package.json electron-api-demos-main@0.0.1 No repository field.
/
> electron-prebuilt@0.30.6 postinstall /home/adam/Projects/electron-api-demos/node_modules/electron-prebuilt
> node install.js

Downloading electron-v0.30.6-linux-x64.zip
[============================================>] 100.0% of 35.99 MB (4 MB/s)
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})

> v8-profiler@5.3.1 preinstall /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-profiler
>  


> v8-debug@0.5.3 preinstall /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-debug
>  


> bufferutil@1.2.1 install /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'

> v8-debug@0.5.3 install /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v46-linux-x64/debug.node" is installed via remote

> v8-profiler@5.3.1 install /home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/adam/Projects/electron-api-demos/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v46-linux-x64/profiler.node" is installed via remote
electron-prebuilt@0.30.6 node_modules/electron-prebuilt
├── extract-zip@1.1.0 (debug@0.7.4, async@0.9.0, mkdirp@0.5.0, yauzl@2.3.1, concat-stream@1.5.0)
└── electron-download@1.1.0 (path-exists@1.0.0, home-path@0.1.2, minimist@1.2.0, mkdirp@0.5.1, debug@2.2.0, mv@2.1.1, nugget@1.5.4)

node-inspector@0.12.3 node_modules/node-inspector
├── path-is-absolute@1.0.0
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── semver@4.3.6
├── serve-favicon@2.3.0 (fresh@0.3.0, ms@0.7.1, etag@1.7.0, parseurl@1.3.0)
├── rc@1.1.1 (strip-json-comments@0.1.3, ini@1.3.4, deep-extend@0.2.11, minimist@1.2.0)
├── glob@5.0.14 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── which@1.1.2 (is-absolute@0.1.7)
├── strong-data-uri@1.0.2 (truncate@1.0.5)
├── yargs@3.25.0 (decamelize@1.0.0, camelcase@1.2.1, window-size@0.1.2, y18n@3.1.0, os-locale@1.4.0, cliui@2.1.0)
├── express@4.13.3 (merge-descriptors@1.0.0, methods@1.1.1, fresh@0.3.0, escape-html@1.0.2, range-parser@1.0.2, vary@1.0.1, array-flatten@1.1.1, etag@1.7.0, cookie@0.1.3, cookie-signature@1.0.6, utils-merge@1.0.0, parseurl@1.3.0, content-type@1.0.1, path-to-regexp@0.1.7, serve-static@1.10.0, content-disposition@0.5.0, depd@1.0.1, qs@4.0.0, finalhandler@0.4.0, type-is@1.6.8, on-finished@2.3.0, proxy-addr@1.0.8, send@0.13.0, accepts@1.2.13)
├── biased-opener@0.2.6 (minimist@1.1.0, x-default-browser@0.3.0, browser-launcher2@0.4.5)
├── ws@0.8.0 (options@0.0.6, ultron@1.0.2, bufferutil@1.2.1, utf-8-validate@1.2.1)
├── v8-debug@0.5.3 (nan@2.0.9, node-pre-gyp@0.6.10)
└── v8-profiler@5.3.1 (nan@2.0.9, node-pre-gyp@0.6.10)
[~/P/electron-api-demos]                                                                                             
‹master› »»»» npm start                                                                                    0|10:32:40

> electron-api-demos-main@0.0.1 start /home/adam/Projects/electron-api-demos
> electron .

[5660:0916/103242:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
module.js:336
    throw err;
          ^
Error: Cannot find module '/home/adam/Projects/electron-api-demos/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/lib/init.js'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:125:18)
    at node.js:960:3
```

**Comment by craigshoemaker** [comment]
Thanks for the heads up. That looks like an issue with Electron directly. I'll have to keep a watch out and see if they address this issue.
